openapi: 3.0.3

info:
  title: base-schemas
  version: v1

paths: {}

components:
  schemas:

    http_response_common_dto:
      type: object
      description: "Http response that the controllers will use."
      properties:
        status_code:
          type: string
          description: "Http status code response"
          example: "200"
        message:
          type: string
          description: "Informative message about http response."
          example: "The user was created successfully."

    new_user_request_dto:
      type: object
      description: "Object DTO for create new user"
      properties:
        full_name:
          type: string
          description: "user full name"
          example: "Diego Estrada"
        user_name:
          type: string
          description: "Username for init session"
          example: "DiegoUser"
        password:
          type: string
          description: "password for init session"
          example: "admin1234"
        email:
          type: string
          description: "user email for send verification code, tokens..."
          example: "diego@gmail.com"
        phone:
          type: string
          description: "user phone for send messages from telegram."
          example: "54114488"