openapi: 3.0.3

info:
  title: user-api
  description: "The **Base V1 API** manage base endpoints"
  version: 1.0.0

#servers:
#  - url: http://localhost:3598
#    description: Servidor local

paths:
  /user:
    post:
      summary: "Endpoint for create new user"
      description: "endpoint to create the approval request for a new account."
      operationId: createUser
      parameters:
        #Request header
        - $ref: "openapi-headers.yml#/components/parameters/x_authorization_header"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "openapi-schemas.yml#/components/schemas/new_user_request_dto"
      responses:
        "201":
          $ref: "openapi-responses.yml#/components/responses/http_common_response"