openapi: 3.0.3

info:
  title: base-responses
  version: v1

paths: {}

components:
  responses:
    http_common_response:
      content:
        application/json:
          schema:
            $ref: "openapi-schemas.yml#/components/schemas/http_response_common_dto"
