CREATE TABLE IF NOT EXISTS `user`(
    id VARCHAR(10) PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    username VARCHAR(20) NOT NULL UNIQUE,
    password VARCHAR(20) NOT NULL,
    email VARCHAR(75) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    ts_insert DATETIME
);